CREATE TABLE todo (
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  CONTENT TEXT NOT NULL,
  USER_ID BIGINT,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user (
  ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)